TypeError: 'zip' object is not subscriptable in the 42 line
TypeError: 'zip' object is not subscriptable. So we can first transform zip objects into Iterable list objects.